# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    handler.category:
        class: AppBundle\Handler\ObjectHandler
        arguments:
            - "AppBundle\\Entity\\Category"
            - "@doctrine.orm.default_entity_manager"
            - "@repository.category"
            - "@serializer"
            - "@validator"

    handler.product:
        class: AppBundle\Handler\ObjectHandler
        arguments:
            - "AppBundle\\Entity\\Product"
            - "@doctrine.orm.default_entity_manager"
            - "@repository.product"
            - "@serializer"
            - "@validator"

    handler.retailer:
        class: AppBundle\Handler\ObjectHandler
        arguments:
            - "AppBundle\\Entity\\Retailer"
            - "@doctrine.orm.default_entity_manager"
            - "@repository.retailer"
            - "@serializer"
            - "@validator"

    repository.category:
        class: AppBundle\Repository\CategoryRepository
        arguments: ["AppBundle\\Entity\\Category"]
        factory: ["@doctrine", "getRepository"]

    repository.retailer:
        class: AppBundle\Repository\RetailerRepository
        arguments: ["AppBundle\\Entity\\Retailer"]
        factory: ["@doctrine", "getRepository"]

    repository.product:
        class: AppBundle\Repository\ProductRepository
        arguments: ["AppBundle\\Entity\\Product"]
        factory: ["@doctrine", "getRepository"]


    # Properly handles:
    #     - deserialization of existing Doctrine Objects (PUT request)
    #     - a NULL constructed/deserialized Object, throws an Exception.
    jms_serializer.doctrine_object_constructor:
        class: AppBundle\Serializer\DoctrineObjectConstructor
        arguments: ["@doctrine", "@jms_serializer.unserialize_object_constructor"]

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor

    jms_serializer.app_bundle.deserialization_subscriber:
        class: AppBundle\Serializer\Subscriber\PreDeserializationSubscriber
        tags:
          - { name: jms_serializer.event_subscriber}
