# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    repository.product:
        class: AppBundle\Repository\ProductRepository
        factory: ["@doctrine", "getRepository"]
        arguments: ["AppBundle\\Entity\\Product"]

    repository.retailer:
        class: AppBundle\Repository\RetailerRepository
        factory: ["@doctrine", "getRepository"]
        arguments: ["AppBundle\\Entity\\Retailer"]

    # Properly handles:
    #     - deserialization of existing Doctrine Objects (PUT request)
    #     - a NULL constructed/deserialized Object, throws an Exception.
    jms_serializer.doctrine_object_constructor:
        class: AppBundle\Serializer\DoctrineObjectConstructor
        arguments: ["@doctrine", "@jms_serializer.unserialize_object_constructor"]

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor

    jms_serializer.app_bundle.deserialization_subscriber:
        class: AppBundle\Serializer\Subscriber\PreDeserializationSubscriber
        tags:
          - { name: jms_serializer.event_subscriber}
